### ISSUE TITLE
Module 2, Programmeren 2, Arrays, Oef 18

### ISSUE THREAD

**Issue by MathiasV-immalle** [MrDanaT/Module-2#1]
Oefening 18 - Arraylists kan niet werken. 
"if (!nietPriem.Contains(i * 2))" --> Voor priem 2 werkt dit. Priem 3 * 2 = 6 en zit er niet in, veelvouden van priem 3 zullen dus niet weerhouden worden. zo voor al de andere priemen ook. je haalt dus alleen alle veelvouden van 2 eruit.

andere vormen nog niet bekeken, maar misschien dezelfde fout?

**Comment by MathiasV-immalle** [comment]
als je
```csharp
for (int i = 2; i < EINDWAARDE; i++)
            {
                if (!nietPriem.Contains(i * 2))
                {
                    for (int j = i * 2; j < EINDWAARDE; j += i)
                    {
                        if (!nietPriem.Contains(j))
                        {
                            nietPriem.Add(j);
                        }
                    }
                }
            }
```
veranderd naar
```csharp
for (int i = 2; i < EINDWAARDE; i++)
            {
                for (int j = i * 2; j < EINDWAARDE; j += i)
                {
                    if (!nietPriem.Contains(j))
                    {
                        nietPriem.Add(j);
                    }
                }
            }
```
werkt het wel.
Het 1e if-je is hier de boosdoener :D

**Comment by MrDanaT** [comment]
heb het bekeken en de if blijft nog altijd noodzakelijk voor een betere complexiteit maar het moest gewoon veranderd worden naar if (... .Contains(i)) :P

**Comment by MrDanaT** [comment]
Zou nu correct moeten zijn

**Comment by MathiasV-immalle** [comment]
ik zie geen verschil met de if erbij, maar werkt prima nu :D

**Comment by MrDanaT** [comment]
checken of 2 er in zit
beginnen met veelvouden van 2: 2,4,6,8,10,12,14,16,18...
checken of 3 er in zit
beginnen met veelvouden van 3: 3,6,9,12,15,18,21,24,27,30...
checken of 4 er in zit
zit er in dus SKIP
checken of 5 er in zit
beginnen met veelvouden van 5: 5,10,15,20,25,30,35,40...
checken of 6 er in zit
zit er in dus SKIP

alle veelvouden van priemgetallen worden geskipt dus da zijn keiveel operaties minder. op limieten <1000 merkt ge het effect amper, ma vanaf dan begint da wel exponentieel te groeien
